todoapp/urls.py
# todoapp/urls.py

from django.urls import path, include
from . import views

app_name = 'todoapp'

urlpatterns = [
	path('', views.all_todolist, name='index'),
    path('user/', include([
        path('login/', views.user_login, name='user_login'),
        path('register/', views.user_register, name='user_register'),
        path('account/', views.user_account, name='user_account'),
        path('logout/', views.logout),
        path('alltodolist/', views.all_todolist, name='all_todolist'),
        path('createtodo/', views.create_todo, name='create_todo'),
        path('edittodo/<id>', views.update_todo, name='update_todo'),
        path('deletetodo/<id>', views.delete_todo, name='delete_todo'),
    ])),
    path('admin_login/', include([
			path('account/',views.login_admin, name='adminlogin'),
	]))
]

todolistproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/', include('todoapp.urls')),
]

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4

def generateUUID():
    return str(uuid4())

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=30)
    about = models.TextField()

    def __str__(self):
        return 'username={0}'.format(self.user.username)

class Todolist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    description = models.TextField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return 'username={0}'.format(self.user.username)

todoapp/forms.py
from django import forms
from .models import *

class RegisterForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	
class AccountForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	about_me = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}), required=False)

class TODOForm(forms.Form):
	title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	status = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'form-control'}), required=False)
	description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}), required=False)

todoapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout as django_logout # Use alias like "django_logout" so that django doesnt get confused on which function to use.
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import JsonResponse
from .helpers import Helpers
from .models import *
from .forms import *

def user_login(request):
	# Redirect if already logged-in
	if request.user.is_authenticated:
		return redirect(Helpers.get_path('user/account'))
	
	if request.method == 'POST':
		# Process the request if posted data are available
		username = request.POST['username']
		password = request.POST['password']
		# Check username and password combination if correct
		user = authenticate(username=username, password=password)
		if user is not None:
			# Success, now let's login the user. 
			login(request, user)
			print('authenticated user')
			# Then redirect to the accounts page.
			return redirect(Helpers.get_path('user/account'))
		else:
			# Incorrect credentials, let's throw an error to the screen.
			return render(request, ('user/login.html'), {'error_message': 'Incorrect username and / or password.'})
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, ('user/login.html'))

def user_account(request):
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	# Create instance of the form and populate it with requests
	form = AccountForm(request.POST)
	
	# Redirect if not logged-in
	if request.user.is_authenticated == False:
		return redirect(Helpers.get_path('user/login')) 
	
	if request.method == 'POST':
		if form.is_valid():	
			# Query data of currently logged-in user.
			user = User.objects.get(username=request.user.username)
			
			# Check if username exists
			if User.objects.filter(username=form.cleaned_data['username']).exists() and user.username != form.cleaned_data['username']:
				err_succ['message'] = 'Username aleady taken, please enter a different one.'
			
			# Check if email exists		
			elif User.objects.filter(email=form.cleaned_data['email']).exists() and user.email != form.cleaned_data['email']:
				err_succ['message'] = 'Email already taken, please enter a different one'
				
			elif form.cleaned_data['old_password'] and form.cleaned_data['password_repeat'] and form.cleaned_data['password']:
				# Check if passwords match
				if form.cleaned_data['password_repeat'] != form.cleaned_data['password']:
					err_succ['message'] = 'New password do not match.'
				
				# Check if old password is correct
				elif not user.check_password(form.cleaned_data['old_password']):
					err_succ['message'] = 'Incorrect old password.'
					
			else:
				user.username = form.cleaned_data['username']
				user.first_name = form.cleaned_data['first_name']
				user.last_name = form.cleaned_data['last_name']
				
				user.member.phone_number = form.cleaned_data['phone_number']
				user.member.about = form.cleaned_data['about_me']
				
				# Save new password if passes above validations
				if form.cleaned_data['password']:
					user.set_password(form.cleaned_data['password'])
				
				# Save posted fields to their respective tables
				user.member.save()
				user.save()
				
				# Show success message
				err_succ['status'] = 1
				err_succ['message'] = 'Account successfully updated.'
			
		return JsonResponse(err_succ)
	else:
		# Let's define intial data that we are going to use to populate our account form.
		user_data = {
			'username': request.user.username, 
			'email': request.user.email, 
			'first_name': request.user.first_name, 
			'last_name': request.user.last_name, 
			'phone_number': request.user.member.phone_number, 
			'about_me': request.user.member.about 
		}
		# Render the account form
		return render(request, Helpers.get_url('user/account.html'), {'form': AccountForm(initial=user_data)})

def user_register(request):
	# Redirect if already logged-in
	if request.user.is_authenticated:
		return redirect(Helpers.get_path('user/account'))
	
	# Create instance of the form and populate it with requests
	form = RegisterForm(request.POST)
	
	# Define default values
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	if request.method == 'POST':
		# check whether it's valid:
		if form.is_valid():
			if User.objects.filter(username=form.cleaned_data['username']).exists():
				err_succ['message'] = 'Username already exists.'
				
			elif User.objects.filter(email=form.cleaned_data['email']).exists():
				err_succ['message'] = 'Email already exists.'
				
			elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
				err_succ['message'] = 'Passwords do not match.'
				
			else:
				# Create the user: 
				user = User.objects.create_user(
					form.cleaned_data['username'], 
					form.cleaned_data['email'], 
					form.cleaned_data['password']
				)
				user.first_name = form.cleaned_data['first_name']
				user.last_name = form.cleaned_data['last_name']
				
				member = Member.objects.create(
					user = user,
					phone_number = form.cleaned_data['phone_number'],
					about = ''
				)
				
				member.save()
				user.save()
				
				# Login the user
				login(request, user)
				
				# return account page URL where we will be redirecting the user.
				err_succ['status'] = 1
				err_succ['message'] = 'Sucessfully registered, redirecting to your account..'
				
		return JsonResponse(err_succ)

   # No post data availabe, let's just show the page.
	else:
		return render(request, Helpers.get_url('user/register.html'), {'form': RegisterForm()})

def logout(request):
	print('in logout view...')
	django_logout(request)
	if request.user.username == 'admin':
		print('in iff......')
		return redirect('/admin_login/account')
	else:
		print('in else.......')
		return redirect(Helpers.get_path('user/login'))

def login_admin(request):
	if request.method == 'GET':
		print('in get request..',)
		return render(request, Helpers.admin_url('login.html'))
	
	if request.method == 'POST':
		print('in post methid...')
		username=request.POST.get('username')
		password =request.POST.get('pass')
		print(username,password)
		try:
			user = authenticate(username = username, password = password)
			user_obj=User.objects.get(username = username)
			if user_obj.username == 'admin':
				print('yes admin here..')
				login(request, user)
				return render(request, Helpers.admin_url('account.html'),{'info': 'You cant login here'})
				return redirect(Helpers.get_path('admin_login/orders'))
			else:
				return render(request, Helpers.admin_url('login.html'),{'info': 'You cant login here'})
		except:
			return render(request, Helpers.admin_url('login.html'),{'data': 'password or username is wrong'})

def all_todolist(request):
	# Redirect if already logged-in
	if request.user.is_authenticated:
		todolists = Todolist.objects.filter(user=request.user)
		# todolists = Todolist.objects.all()
		print(todolists)
		return render(request, ('user/todolist.html'), {'todolists':todolists})
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, ('user/login.html'))
	
def create_todo(request):
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	# Create instance of the form and populate it with requests
	form = TODOForm(request.POST)

	# Redirect if already logged-in
	if request.user.is_authenticated:	
		if request.method == 'POST':
			if form.is_valid():	
				# Query data of currently logged-in user.
				user = User.objects.get(username=request.user.username)

				todolist = Todolist.objects.create(
					user = user,
					title = form.cleaned_data['title'],
					description = form.cleaned_data['description'],
					status = form.cleaned_data['status']
				)
				
				# Save posted fields to their respective tables
				todolist.save()
					
				# Show success message
				err_succ['status'] = 1
				err_succ['message'] = 'TODO successfully Added.'
				
			return JsonResponse(err_succ)
		else:
			return render(request, ('user/createtodo.html'), {'form': TODOForm})
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, ('user/login.html'))

def update_todo(request, id):
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	# Create instance of the form and populate it with requests

	# Redirect if already logged-in
	if request.user.is_authenticated:	
		if request.method == 'POST':
			form = TODOForm(request.POST)
			if form.is_valid():	
				ttodolist = Todolist.objects.get(id=id)
				ttodolist.title = form.cleaned_data['title']
				ttodolist.status = form.cleaned_data['status']
				ttodolist.description = form.cleaned_data['description']
				# Save posted fields to their respective tables
				ttodolist.save()
					
				# Show success message
				err_succ['status'] = 1
				err_succ['message'] = 'TODO successfully Updated.'
				
			return JsonResponse(err_succ)
		else:
			ttodolist = get_object_or_404(Todolist, id=id)
			print(ttodolist)
			if ttodolist.status == 1:
				list_data = {
					'title': ttodolist.title, 
					'status': ttodolist.status, 
					'description': ttodolist.description 
				}
			else:
				list_data = {
					'title': ttodolist.title, 
					'description': ttodolist.description 
				}
			return render(request, ('user/edittodo.html'), {'listid': ttodolist.id,'form': TODOForm(initial=list_data)})
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, ('user/login.html'))

def delete_todo(request, id):
	# Redirect if already logged-in
	if request.user.is_authenticated:	
		ttodolist = get_object_or_404(Todolist, id=id)
		ttodolist.delete()
		return redirect(Helpers.get_path('user/alltodolist'))
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, ('user/login.html'))

todoapp/templates/user/account.html
{% extends "base.html" %}

{% block content %}
	<div class="container wave-box-wrapper">
		<div class="wave-box"></div>
		<form action="{% url 'todoapp:user_account' %}" method="post" class="update-account">
			{% csrf_token %}
			<div class="col-md-10 offset-md-1">
				<div class="card">
					<div class="card-header">My Account</div>
					<div class="card-body">
						<div class="form-group row">
							<label for="{{ form.username.id_for_label }}" class="col-md-3 control-label text-md-right">Username<span class="text-danger">*</span>:</label>
							<div class="col-md-7">
								{{ form.username }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.email.id_for_label }}" class="col-md-3 control-label text-md-right">Email<span class="text-danger">*</span>:</label>
							<div class="col-md-7">
								{{ form.email }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.old_password.id_for_label }}" class="col-md-3 control-label text-md-right">Old password:</label>
							<div class="col-md-7">
								{{ form.old_password }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password.id_for_label }}" class="col-md-3 control-label text-md-right">New password:</label>
							<div class="col-md-7">
								{{ form.password }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password_repeat.id_for_label }}" class="col-md-3 control-label text-md-right">Confirm New password:</label>
							<div class="col-md-7">
								{{ form.password_repeat }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.first_name.id_for_label }}" class="col-md-3 control-label text-md-right">First Name:</label>
							<div class="col-md-7">
								{{ form.first_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.last_name.id_for_label }}" class="col-md-3 control-label text-md-right">Last Name:</label>
							<div class="col-md-7">
								{{ form.last_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.phone_number.id_for_label }}" class="col-md-3 control-label text-md-right">Phone Number:</label>
							<div class="col-md-7">
								{{ form.phone_number }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.about_me.id_for_label }}" class="col-md-3 control-label text-md-right">About Me:</label>
							<div class="col-md-7">
								{{ form.about_me }}
							</div>
						</div>
						<div class="col-md-7 offset-md-3 px-0 px-xl-2">
							<input type="submit" value="Update" class="btn btn-primary">
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

todoapp/templates/user/createtodo.html
{% extends "base.html" %}

{% block content %}
	<div class="container wave-box-wrapper">
		<div class="wave-box"></div>
		<form action="{% url 'todoapp:create_todo' %}" method="post" class="create-todo" id="createt_odo">
			{% csrf_token %}
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<div class="card-header">Create</div>
					<div class="card-body">
						<div class="form-group row">
							<label for="{{ form.title.id_for_label }}" class="col-md-3 control-label text-md-right">Title<span class="text-danger">*</span>:</label>
							<div class="col-md-7">
								{{ form.title }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.status.id_for_label }}" class="col-md-3 control-label text-md-right">Status:</label>
							<div class="col-md-7">
								{{ form.status }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.description.id_for_label }}" class="col-md-3 control-label text-md-right">Description:</label>
							<div class="col-md-7">
								{{ form.description }}
							</div>
						</div>
						<div class="col-md-7 offset-md-3 px-0 px-xl-2">
							<input type="submit" value="Create" class="btn btn-primary">
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

todoapp/templates/user/edittodo.html
{% extends "base.html" %}

{% block content %}
	<div class="container wave-box-wrapper">
		<div class="wave-box"></div>
		<form action="{% url 'todoapp:update_todo' listid %}" method="post" class="update-todo" id="update-todo">
			{% csrf_token %}
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<div class="card-header">Edit</div>
					<div class="card-body">
						<div class="form-group row">
							<label for="{{ form.title.id_for_label }}" class="col-md-3 control-label text-md-right">Title<span class="text-danger">*</span>:</label>
							<div class="col-md-7">
								{{ form.title }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.status.id_for_label }}" class="col-md-3 control-label text-md-right">Status:</label>
							<div class="col-md-7">
								{{ form.status }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.description.id_for_label }}" class="col-md-3 control-label text-md-right">Description:</label>
							<div class="col-md-7">
								{{ form.description }}
							</div>
						</div>
						<div class="col-md-7 offset-md-3 px-0 px-xl-2">
							<input type="submit" value="Update" class="btn btn-primary">
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

todoapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<form action="{% url 'todoapp:user_login' %}" method="post">
			{% csrf_token %}
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<div class="card-header">Login</div>
					<div class="card-body">
						{% if error_message %}
							<div class="alert alert-danger" role="alert">{{ error_message }}</div>
						{% endif %}
						<div class="form-group row">
							<label for="username" class="col-md-4 control-label text-md-right">Username:</label>
							<div class="col-md-6">
								<input name="username" value="" type="text" class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label for="password" class="col-md-4 control-label text-md-right">Password:</label>
							<div class="col-md-6">
								<input name="password" type="password" class="form-control" />
							</div>
						</div>
						<div class="col-md-6 offset-md-4 px-0 px-xl-2">
							<input name="login" type="submit" value="Login" class="btn btn-primary" /> &nbsp; 
							<a href="/todoapp/user/register">or Register</a>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

todoapp/templates/user/register.html
{% extends "base.html" %}

{% block content %}
	<div class="container wave-box-wrapper">
		<div class="wave-box"></div>
		<form action="{% url 'todoapp:user_register' %}" method="post" class="create-account">
			{% csrf_token %}
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<div class="card-header">Register</div>
					<div class="card-body">
						<div class="form-group row">
							<label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-md-right">Username<span class="text-red">*</span>:</label>
							<div class="col-md-6">
								{{ form.username }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-md-right">Email<span class="text-red">*</span>:</label>
							<div class="col-md-6">
								{{ form.email }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-md-right">Password<span class="text-red">*</span>:</label>
							<div class="col-md-6">
								{{ form.password }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-md-right">Confirm password:</label>
							<div class="col-md-6">
								{{ form.password_repeat }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-md-right">First Name:</label>
							<div class="col-md-6">
								{{ form.first_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-md-right">Last Name:</label>
							<div class="col-md-6">
								{{ form.last_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.phone_number.id_for_label }}" class="col-md-4 control-label text-md-right">Phone Number:</label>
							<div class="col-md-6">
								{{ form.phone_number }}
							</div>
						</div>
						<div class="col-md-6 offset-md-4 px-0 px-xl-2">
							<input type="submit" value="Register" class="btn btn-primary">
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

todoapp/templates/user/todolist.html
{% extends "base.html" %}

{% block content %}
	<div class="container wave-box-wrapper">
		<div class="wave-box"></div>
		<div class="row">
			<div class="col-sm-12 my-4">
				<div class="card">
					<div class="card-header">
						<h4>TODO List</h4>
					</div>
					<div class="card-body">
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover" id='table_todolist'>
								<thead>
									<tr>
										<th>Title</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									{% for item in todolists %}
										<tr>
										<td>{{item.title}}</td>
										<td>
											{% comment %} <form method="post" action="#" class="form-inline">
												<input type="hidden" name="action" value="edit" />
												<input type="hidden" name="id" value="{{ item.id }}" /> {% endcomment %}
												{% if item.status == 1 %}
												<p>Completed</p>
												<input type="hidden" name="id" value="{{ item.id }}" />
												{% comment %} <input type="hidden" class="status" name="status" value="{{item.status}}" /> {% endcomment %}
												{% else %}
												<p>Not Completed</p>
												<input type="hidden" name="id" value="{{ item.id }}" />
												{% comment %} <input type="hidden" class="status" name="status" value="{{item.status}}" /> {% endcomment %}
												{% endif %}
											{% comment %} </form> {% endcomment %}
										</td>
										<td>
											<a href="{% url 'todoapp:update_todo' item.id %}" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Edit</a>
											<a href="{% url 'todoapp:delete_todo' item.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-floppy-save"></span> Delete</a>
										</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}